blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/Developer-Kommunity-24/community-website
    about: Please use GitHub discussions for feature requests.
